routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/**
 * Admin routes
 */
Route::group(['prefix' => 'company', 'middleware' => ['company'], 'as' => 'company.' ], function () {
    Route::namespace('Company')->group(function () {
        Route::get('/','CompanyController@index')->name('dashboard');
        Route::namespace('Brands')->group(function()
        {
            Route::resource('brands', 'BrandController');
        });
        Route::namespace('Orders')->group(function()
        {
            Route::resource('orders', 'OrderController');
        });
        Route::namespace('Products')->group(function () {
            Route::resource('products', 'ProductController');
            Route::get('remove-image-product', 'ProductController@removeImage')->name('product.remove.image');
            Route::get('remove-image-thumb', 'ProductController@removeThumbnail')->name('product.remove.thumb');
        });
    });
});

Route::get('company/view-profile/{id}','Admin\Company\CompanyController@show');
Route::get('company/edit-profile/{id}/edit','Admin\Company\CompanyController@edit');
Route::patch('company/{id}','Admin\Company\CompanyController@update');
Route::get('company/change-password/{id}','Admin\Company\CompanyController@changePassword');
Route::patch('company/update-password/{id}','Admin\Company\CompanyController@updatePassword');
Route::get('company/addresses/{id}','Admin\Company\CompanyController@showAddresses');
Route::get('company/address/create','Admin\Addresses\AddressController@createCompanyAddress');
Route::post('company/address/{id}','Admin\Addresses\AddressController@storeCompanyAddress');
Route::get('company/register','Admin\Company\CompanyController@create');
Route::post('company','Admin\Company\CompanyController@store');

Route::get('questionAnswer', 'Admin\QuestionAnswerController@index');
Route::get('questionAnswer/create', 'Admin\QuestionAnswerController@create');
Route::post('questionAnswer/store', 'Admin\QuestionAnswerController@store');
Route::get('questionAnswer/edit/{id}', 'Admin\QuestionAnswerController@edit');
Route::patch('questionAnswer/update/{id}', 'Admin\QuestionAnswerController@update');
Route::delete('questionAnswer/delete/{id}', 'Admin\QuestionAnswerController@destroy');

/**
 * Admin routes
 */
Route::namespace('Admin')->group(function () {
    Route::get('admin/login', 'LoginController@showLoginForm')->name('admin.login');
    Route::post('admin/login', 'LoginController@login')->name('admin.login');
    Route::get('admin/logout', 'LoginController@logout')->name('admin.logout');
});
Route::group(['prefix' => 'admin', 'middleware' => ['employee'], 'as' => 'admin.' ], function () {
    Route::namespace('Admin')->group(function () {
        Route::group(['middleware' => ['role:admin|superadmin|clerk, guard:employee']], function () {
            Route::get('/', 'DashboardController@index')->name('dashboard');
            Route::namespace('Products')->group(function () {
                Route::resource('products', 'ProductController');
                Route::get('requests','ProductController@requests')->name('products.requests');
                Route::get('products/requests/{id}','ProductController@approve')->name('products.requests.approve');
                Route::get('remove-image-product', 'ProductController@removeImage')->name('product.remove.image');
                Route::get('remove-image-thumb', 'ProductController@removeThumbnail')->name('product.remove.thumb');
            });
            Route::namespace('Customers')->group(function () {
                Route::resource('customers', 'CustomerController');
                Route::resource('customers.addresses', 'CustomerAddressController');
            });
            Route::namespace('Categories')->group(function () {
                Route::resource('categories', 'CategoryController');
                Route::get('remove-image-category', 'CategoryController@removeImage')->name('category.remove.image');
            });
            Route::namespace('Company')->group(function () {
                Route::get('acceptCompany', 'CompanyController@acceptCompany')->name('company.acceptCompany');
                Route::patch('approveCompany/{id}', 'CompanyController@approveCompany')->name('company.approveCompany');
                Route::get('deactivateCompany', 'CompanyController@unauthorizedCompany')->name('company.unauthorizedCompany');
                Route::patch('deactivateCompany/{id}', 'CompanyController@unApproveCompany')->name('company.unApproveCompany');
            });
            Route::namespace('Banner')->group(function () {
                Route::get('createBanner', 'BannerController@createBanner')->name('banner.createBanner');
                Route::post('addBanner', 'BannerController@addBanner')->name('banner.addBanner');
            });
            Route::namespace('Review')->group(function () {
                Route::get('reviews/accept', 'ReviewController@accept')->name('reviews.accept');
                Route::get('reviews/approve/{id}', 'ReviewController@approve')->name('reviews.approve');
            });
            Route::namespace('Auction')->group(function () {
                Route::get('auction', 'AuctionController@index')->name('auction.index');
                Route::get('auction/approved', 'AuctionController@approvedAuction')->name('auction.approved');
                Route::get('auction/unapproved', 'AuctionController@unapprovedAuction')->name('auction.unapproved');
                Route::get('auction/approve/{id}', 'AuctionController@approve')->name('auction.approve');
            });
           
            Route::namespace('Promotion')->group(function () {
                Route::get('editPromotion', 'PromotionController@editPromotion')->name('promotion.editPromotion');
                Route::put('updatePromotion', 'PromotionController@updatePromotion')->name('promotion.updatePromotion');
            });
            Route::namespace('Orders')->group(function () {
                Route::resource('orders', 'OrderController');
                Route::resource('order-statuses', 'OrderStatusController');
                Route::get('orders/{id}/invoice', 'OrderController@generateInvoice')->name('orders.invoice.generate');
            });
            Route::resource('addresses', 'Addresses\AddressController');
            Route::resource('countries', 'Countries\CountryController');
            Route::resource('countries.provinces', 'Provinces\ProvinceController');
            Route::resource('countries.provinces.cities', 'Cities\CityController');
            Route::resource('couriers', 'Couriers\CourierController');
            Route::resource('attributes', 'Attributes\AttributeController');
            Route::resource('attributes.values', 'Attributes\AttributeValueController');
            Route::resource('brands', 'Brands\BrandController');

        });
        Route::group(['middleware' => ['role:admin|superadmin, guard:employee']], function () {
            Route::resource('employees', 'EmployeeController');
            Route::get('employees/{id}/profile', 'EmployeeController@getProfile')->name('employee.profile');
            Route::put('employees/{id}/profile', 'EmployeeController@updateProfile')->name('employee.profile.update');
            Route::resource('roles', 'Roles\RoleController');
            Route::resource('permissions', 'Permissions\PermissionController');
        });
    });
});

/**
 * Frontend routes
 */
Auth::routes();
Route::namespace('Auth')->group(function () {
    Route::get('cart/login', 'CartLoginController@showLoginForm')->name('cart.login');
    Route::post('cart/login', 'CartLoginController@login')->name('cart.login');
    Route::get('logout', 'LoginController@logout');
});

Route::namespace('Front')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::group(['middleware' => ['auth', 'web']], function () {

        Route::namespace('Payments')->group(function () {
            Route::get('bank-transfer', 'BankTransferController@index')->name('bank-transfer.index');
            Route::post('bank-transfer', 'BankTransferController@store')->name('bank-transfer.store');
        });

        Route::namespace('Addresses')->group(function () {
            Route::resource('country.state', 'CountryStateController');
            Route::resource('state.city', 'StateCityController');
        });

        Route::get('accounts', 'AccountsController@index')->name('accounts');
        Route::get('checkout', 'CheckoutController@index')->name('checkout.index');
        Route::post('checkout', 'CheckoutController@store')->name('checkout.store');
        Route::get('checkout/execute', 'CheckoutController@executePayPalPayment')->name('checkout.execute');
        Route::post('checkout/execute', 'CheckoutController@charge')->name('checkout.execute');
        Route::get('checkout/cancel', 'CheckoutController@cancel')->name('checkout.cancel');
        Route::get('checkout/success', 'CheckoutController@success')->name('checkout.success');
        Route::resource('customer.address', 'CustomerAddressController');
    });
    Route::resource('cart', 'CartController');
    Route::get("category/{slug}", 'CategoryController@getCategory')->name('front.category.slug');
    Route::get("search", 'ProductController@search')->name('search.product');
    Route::get("{product}", 'ProductController@show')->name('front.get.product');

});

app/Http/Controllers/Admin/Mall/ProductController.php
<?php

namespace App\Http\Controllers\Admin\Mall;


use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use MallProduct;

class ProductController extends Controller
{
    /**
     * return all product for currant store
     * @return Product
     * @author Amr Degheidy
     */
    public function index()
    {
        $store = $this->auth('store');
        return $store->products();

    }
    /**
     * return view to create product
     * @return View
     * @author Amr Degheidy
     */
    public function create()
    {
        return view('create product');
    }
    /**
     * store product for stor 
     * @param Request
     * @author Amr Degheidy
     */
    public function store(Request $request)
    {
        $validate = $request->validate([
            'name'=>'required',
            'cover'=>'required|image',
            'price  '=>'required',
            'description'=>'required',
            
        ]);
        $request->store_id = $this->auth('store');
        if($validate->fails())
        {
            session()->flash('message','Cannot Create Product');
            return redirect()->back()->withErrors($validate)->withInput();
        }
        session()->flash('message','Product Created Successfully');
        return redirect()->route('index');
    }
    /**
     * edit product for store
     * @param Product $id
     * @return View with data for product
     * @author Amr Degheidy
     */
    public function edit($id)
    {
        $product = MallProduct::findOrFail($id);
        return view('edit view',compact($product));

    }
    /**
     * update product
     * @param Request
     * @return Route with data
     * @author Amr Degheidy
     */
    public function update(Request $request)
    {
        $validate = $request->validate([
            'name'=>'required',
            'cover'=>'required|image',
            'price'=>'required',
            'description'=>'required'
        ]);
        if($validate->fails())
        {
            session()->flash('message','Product Cannot Updated ');
            return redirect()->back()->withErrors($validate)->withInput();
        }
        session()->flash('message','Product Created Successfully');
        return redirect()->route(' index route');
    }
    /**
     * show product
     * @param Product $id
     * @return View
     * @author Amr Degheidy
     */
    public function show($id)
    {
        $product = MallProduct::findOrFail($id);
        return view('show view', compact($product));
    }

    /**
     * delete product
     * @param Product $id
     * @return Route
     * @author Amr Degheidy
     */
    public function destroy($id)
    {
        $product = MallProduct::findOrFail($id);
        $product->destroy();
        session()->flash('message','Product Deleted Successfully');
        return redirect()->route('index route');
    }
}

app/Http/Controllers/Api/Company/CompanyController.php
<?php

namespace App\Http\Controllers\Api\Company;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Shop\Companies\Company;
use App\Shop\Companies\Repositories\Interfaces\CompanyRepositoryInterface;
use App\Shop\Companies\Repositories\CompanyRepository;
use App\Http\Resources\Product\ProductResource;

class CompanyController extends Controller
{
    //

    /**
     * @var CompanyRepositoryInterface
     */
    protected $companyRepo;

    public function __construct(CompanyRepositoryInterface $companyRepo)
    {
        $this->companyRepo = $companyRepo;
    }
    /**
     * return company product
     * @param Company $id
     * @return Response
     */
    public function index(int $id)
    {
        $company = $this->companyRepo->findCompanyById($id);
        $companyRepo = new CompanyRepository($company);
        $products = ProductResource::collection($companyRepo->findProducts())->collection->toArray();
        return response()->success($products);;
    }


}

app/Http/Controllers/Api/Mall/ProductController.php
<?php

namespace App\Http\Controllers\Api\Mall;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Resources\Mall\ProductResource;
use App\Mall\Product;
use App\Mall\Store;

class ProductController extends Controller
{
    //
    /**
     * return product for specific store in specif mall
     * @param Mall $mallId
     * @param Store $storeId
     */
    public function index($mallId,$storeId)
    {
        $store = Store::find($storeId);
        $products = $store->products;


        return response()->success(ProductResource::collection($products)->collection);
    }
    /**
     * return product details
     * @param Mall $mallId
     * @param Store $storeId
     * @param Product $productId
     * @return Product data
     */
    public function show($mallId,$storeId,$productId)
    {
        $product = Product::find($productId);
        return response()->success($product);
    }
}

app/Http/Controllers/Company/CompanyController.php
<?php

namespace App\Http\Controllers\Company;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CompanyController extends Controller
{
    //
    /**
     * Get All Companies
     * @return view
     */
    public function index()
    {        
        $breadcumb = [
            ["name" => "Dashboard", "url" => route("company.dashboard"), "icon" => "fa fa-dashboard"],
            ["name" => "Home", "url" => route("company.dashboard"), "icon" => "fa fa-home"],
        ];
        populate_breadcumb($breadcumb);
        return view('company.dashboard', [ 'company' => auth('company')->user() , 'breadcumbs' => $breadcumb]);    
    }

}

app/Http/Controllers/Front/ProductController.php
<?php

namespace App\Http\Controllers\Front;

use App\Shop\Products\Product;
use App\Shop\Products\Repositories\Interfaces\ProductRepositoryInterface;
use App\Http\Controllers\Controller;
use App\Shop\Products\Transformations\ProductTransformable;

class ProductController extends Controller
{
    use ProductTransformable;

    /**
     * @var ProductRepositoryInterface
     */
    private $productRepo;

    /**
     * ProductController constructor.
     * @param ProductRepositoryInterface $productRepository
     */
    public function __construct(ProductRepositoryInterface $productRepository)
    {
        $this->productRepo = $productRepository;
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function search()
    {
        if (request()->has('q') && request()->input('q') != '') {
            $list = $this->productRepo->searchProduct(request()->input('q'));
        } else {
            $list = $this->productRepo->listProducts();
        }

        $products = $list->where('status', 1)->map(function (Product $item) {
            return $this->transformProduct($item);
        });

        return view('front.products.product-search', [
            'products' => $this->productRepo->paginateArrayResults($products->all(), 10)
        ]);
    }

    /**
     * Get the product
     *
     * @param string $slug
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(string $slug)
    {
        $product = $this->productRepo->findProductBySlug(['slug' => $slug]);
        $images = $product->images()->get();
        $category = $product->categories()->first();
        $productAttributes = $product->attributes;

        return view('front.products.product', compact(
            'product',
            'images',
            'productAttributes',
            'category'
        ));
    }
}

resources/views/company/products/attributes.blade.php
@if(!$productAttributes->isEmpty())
    <p class="alert alert-info">You can only set 1 default combination</p>
    <ul class="list-unstyled">
        <li>
            <table class="table">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Quantity</th>
                    <th>Price</th>
                    <th>Sale Price</th>
                    <th>Attributes</th>
                    <th>Is default?</th>
                    <th>Remove</th>
                </tr>
                </thead>
                <tbody>
                @foreach($productAttributes as $pa)
                    <tr>
                        <td>{{ $pa->id }}</td>
                        <td>{{ $pa->quantity }}</td>
                        <td>{{ $pa->price }}</td>
                        <td>{{ $pa->sale_price }}</td>
                        <td>
                            <ul class="list-unstyled">
                                @foreach($pa->attributesValues as $item)
                                    <li>{{ $item->attribute->name }} : {{ $item->value }}</li>
                                @endforeach
                            </ul>
                        </td>
                        <td>
                            @if($pa->default == 1)
                                <button class="btn btn-success"><i class="fa fa-check"></i></button>
                            @else
                                <button class="btn btn-danger"><i class="fa fa-remove"></i></button>
                            @endif
                        </td>
                        <td class="btn-group">
                            <a
                                    onclick="return confirm('Are you sure?')"
                                    href="{{ route('company.products.edit', [$product->id, 'combination' => 1, 'delete' => 1, 'pa' => $pa->id]) }}"
                                    class="btn btn-sm btn-danger">
                                <i class="fa fa-trash"></i> Delete
                            </a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </li>
    </ul>
@else
    <p class="alert alert-warning">No combination yet.</p>
@endif

resources/views/company/products/create.blade.php
@extends('company.layouts.company.app')

@section('content')
<!-- Main content -->
<section class="content" style="margin-top: 25px;" >
    @include('layouts.errors-and-messages')
    <div style="margin:0 auto; width:50%; border:none; text-align:center;">
        <h2>Add Product</h2>
    </div>

    @if( ! $brands->isEmpty() )
        <div class="box customBox">
            <form action="{{ route('company.products.store') }}" method="post" class="form" enctype="multipart/form-data">
                <div class="box-body">
                    {{ csrf_field() }}

                    <div class="form-group group">
                        <label for="parent">Category <span class="text-danger">*</span></label>
                        <select name="parent" id="parent" class="form-control">
                            <option value="0">Select</option>
                            @foreach($categories as $category)
                                @if($category->children->count() >= 1 )
                                    <optgroup label="{{ $category->name }}">
                                        @foreach($category->children as $child)
                                            <option value="{{$child->id}}">
                                                {{$child->name}}
                                            </option>
                                        @endforeach
                                    </optgroup>
                                @endif
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group group">
                        <label for="name">Product Name <span class="text-danger">*</span></label>
                        <input type="text" name="name" id="name" placeholder="Name" class="form-control"
                               value="{{ old('name') }}">
                    </div>

                    <div class="form-group group">
                        <label for="description">Description </label>
                        <textarea class="form-control" name="description" id="description" rows="5"
                                  placeholder="Description">{{ old('description') }}</textarea>
                    </div>

                    <div class="form-group group">
                        <label for="cover">Cover <span class="text-danger">*</span></label>
                        <input type="file" name="cover" id="cover" style="padding:0px; border: none; outline: none;" class="form-control">
                    </div>

                    <div class="form-group group">
                        <label for="image">Images <span class="text-danger">*</span></label>
                        <input type="file" name="image[]" id="image" style="padding:0px; border: none; outline: none;" class="form-control" multiple>
                        <small class="text-warning">You can use ctr (cmd) to select multiple images</small>
                    </div>

                    <div class="form-group group">
                        <label for="quantity">Quantity <span class="text-danger">*</span></label>
                        <input type="text" name="quantity" id="quantity" placeholder="Quantity" class="form-control"
                               value="{{ old('quantity') }}">
                    </div>

                    <div class="form-group group">
                        <label for="price">Price <span class="text-danger">*</span></label>
                        <input type="text" name="price" id="price" placeholder="Price" class="form-control"
                               value="{{ old('price') }}">
                    </div>

                    <div class="form-group group">
                        <label for="sale_price">Price After Discount<span class="text-danger">*</span></label>
                        <input type="text" name="sale_price" id="sale_price" placeholder="Price" class="form-control" value="{{ old('price') }}">
                    </div>

                    <div class="form-group group">
                        <label for="sku">SKU <span class="text-danger">*</span></label>
                        <input type="text" name="sku" id="sku" placeholder="xxxxx" class="form-control" value="{{ old('sku') }}">
                    </div>

                    <div class="form-group group">
                        <label for="length">Length <span class="text-danger">*</span></label>
                        <input type="text" name="length" id="length" placeholder="length" class="form-control" value="">
                    </div>

                    <div class="form-group group">
                        <label for="width">Width <span class="text-danger">*</span></label>
                        <input type="text" name="width" id="width" placeholder="width" class="form-control" value="">
                    </div>

                    <div class="form-group group">
                        <label for="height">Height <span class="text-danger">*</span></label>
                        <input type="text" name="height" id="height" placeholder="height" class="form-control" value="">
                    </div>

                    <div class="form-group group">
                        <label for="distance_unit">Distance Unit <span class="text-danger">*</span></label>
                        <input type="text" name="distance_unit" id="distance_unit" placeholder="distance unit" class="form-control" value="">
                    </div>

                    @if( ! $brands->isEmpty() )
                        <div class="form-group group">
                            <label for="brand_id">Brand <span class="text-danger">*</span></label>
                            <select name="brand" id="brand" class="form-control select2">
                                <option value=""></option>
                                @foreach($brands as $brand)
                                    <option @if(old('brand_id')==$brand->id) selected="selected" @endif
                                    value="{{ $brand->id }}">{{ $brand->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    @endif

                    <div class="form-group group">
                        @include('company.shared.status-select', ['status' => 0])
                    </div>

                    <div class="form-group group">
                        @include('company.shared.attribute-select', [compact('default_weight')])
                    </div>

                    <div class="box-footer" style="text-align:center;">
                        <div class="btn-group">
                            <a href="{{ route('company.products.index') }}" class="btn btn-default">Back</a>
                            <button type="submit" class="btn btn-primary">Create</button>
                        </div>
                    </div>
            </form>
        </div>
    @else
        <div class="alert alert-secondary alert-warning" role="alert" style="font-size: 15px;">
            You need to add Brands before adding product <a href="{{ route('company.brands.create') }}">Create Brand</a>
        </div>
    @endif


    <!-- /.box -->

</section>
<!-- /.content -->
@endsection

resources/views/company/products/list.blade.php
@extends('company.layouts.company.app')

@section('content')
    <!-- Main content -->
    <section class="content" style="margin-top: 25px;" >
    @include('layouts.errors-and-messages')
    <!-- Default box -->
        @if(!$products->isEmpty())
            <div class="box">
                <div class="box-body">
                    <h2>Products</h2>
                    @include('layouts.search', ['route' => route('company.products.index')])
                    @include('company.shared.products')
                    {{ $products->links() }}
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        @endif

    </section>
    <!-- /.content -->
@endsection

resources/views/company/products/show.blade.php
@extends('company.layouts.company.app')

@section('content')
    <!-- Main content -->
    <section class="content" style="margin-top: 25px;" >

    @include('layouts.errors-and-messages')
    <!-- Default box -->
        @if($product)
            <div class="box">
                <div class="box-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <td class="col-md-2">Name</td>
                            <td class="col-md-3">Description</td>
                            <td class="col-md-3">Cover</td>
                            <td class="col-md-2">Quantity</td>
                            <td class="col-md-2">Price</td>
                        </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>{{ $product->name }}</td>
                                <td>{{ $product->description }}</td>
                                <td>
                                    @if(isset($product->cover))
                                        <img src="{{ $product->cover }}" class="img-responsive" alt="">
                                    @endif
                                </td>
                                <td>{{ $product->quantity }}</td>
                                <td>{{ config('cart.currency') }} {{ $product->price }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <div class="btn-group">
                        <a href="{{ route('company.products.index') }}" class="btn btn-default btn-sm">Back</a>
                    </div>
                </div>
            </div>
            <!-- /.box -->
        @endif

    </section>
    <!-- /.content -->
@endsection