routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/**
 * Admin routes
 */
Route::group(['prefix' => 'company', 'middleware' => ['company'], 'as' => 'company.' ], function () {
    Route::namespace('Company')->group(function () {
        Route::get('/','CompanyController@index')->name('dashboard');
        Route::namespace('Brands')->group(function()
        {
            Route::resource('brands', 'BrandController');
        });
        Route::namespace('Orders')->group(function()
        {
            Route::resource('orders', 'OrderController');
        });
        Route::namespace('Products')->group(function () {
            Route::resource('products', 'ProductController');
            Route::get('remove-image-product', 'ProductController@removeImage')->name('product.remove.image');
            Route::get('remove-image-thumb', 'ProductController@removeThumbnail')->name('product.remove.thumb');
        });
    });
});

Route::get('company/view-profile/{id}','Admin\Company\CompanyController@show');
Route::get('company/edit-profile/{id}/edit','Admin\Company\CompanyController@edit');
Route::patch('company/{id}','Admin\Company\CompanyController@update');
Route::get('company/change-password/{id}','Admin\Company\CompanyController@changePassword');
Route::patch('company/update-password/{id}','Admin\Company\CompanyController@updatePassword');
Route::get('company/addresses/{id}','Admin\Company\CompanyController@showAddresses');
Route::get('company/address/create','Admin\Addresses\AddressController@createCompanyAddress');
Route::post('company/address/{id}','Admin\Addresses\AddressController@storeCompanyAddress');
Route::get('company/register','Admin\Company\CompanyController@create');
Route::post('company','Admin\Company\CompanyController@store');

Route::get('questionAnswer', 'Admin\QuestionAnswerController@index');
Route::get('questionAnswer/create', 'Admin\QuestionAnswerController@create');
Route::post('questionAnswer/store', 'Admin\QuestionAnswerController@store');
Route::get('questionAnswer/edit/{id}', 'Admin\QuestionAnswerController@edit');
Route::patch('questionAnswer/update/{id}', 'Admin\QuestionAnswerController@update');
Route::delete('questionAnswer/delete/{id}', 'Admin\QuestionAnswerController@destroy');

/**
 * Admin routes
 */
Route::namespace('Admin')->group(function () {
    Route::get('admin/login', 'LoginController@showLoginForm')->name('admin.login');
    Route::post('admin/login', 'LoginController@login')->name('admin.login');
    Route::get('admin/logout', 'LoginController@logout')->name('admin.logout');
});
Route::group(['prefix' => 'admin', 'middleware' => ['employee'], 'as' => 'admin.' ], function () {
    Route::namespace('Admin')->group(function () {
        Route::group(['middleware' => ['role:admin|superadmin|clerk, guard:employee']], function () {
            Route::get('/', 'DashboardController@index')->name('dashboard');
            Route::namespace('Products')->group(function () {
                Route::resource('products', 'ProductController');
                Route::get('requests','ProductController@requests')->name('products.requests');
                Route::get('products/requests/{id}','ProductController@approve')->name('products.requests.approve');
                Route::get('remove-image-product', 'ProductController@removeImage')->name('product.remove.image');
                Route::get('remove-image-thumb', 'ProductController@removeThumbnail')->name('product.remove.thumb');
            });
            Route::namespace('Customers')->group(function () {
                Route::resource('customers', 'CustomerController');
                Route::resource('customers.addresses', 'CustomerAddressController');
            });
            Route::namespace('Categories')->group(function () {
                Route::resource('categories', 'CategoryController');
                Route::get('remove-image-category', 'CategoryController@removeImage')->name('category.remove.image');
            });
            Route::namespace('Company')->group(function () {
                Route::get('acceptCompany', 'CompanyController@acceptCompany')->name('company.acceptCompany');
                Route::patch('approveCompany/{id}', 'CompanyController@approveCompany')->name('company.approveCompany');
                Route::get('deactivateCompany', 'CompanyController@unauthorizedCompany')->name('company.unauthorizedCompany');
                Route::patch('deactivateCompany/{id}', 'CompanyController@unApproveCompany')->name('company.unApproveCompany');
            });
            Route::namespace('Banner')->group(function () {
                Route::get('createBanner', 'BannerController@createBanner')->name('banner.createBanner');
                Route::post('addBanner', 'BannerController@addBanner')->name('banner.addBanner');
            });
            Route::namespace('Review')->group(function () {
                Route::get('reviews/accept', 'ReviewController@accept')->name('reviews.accept');
                Route::get('reviews/approve/{id}', 'ReviewController@approve')->name('reviews.approve');
            });
            Route::namespace('Auction')->group(function () {
                Route::get('auction', 'AuctionController@index')->name('auction.index');
                Route::get('auction/approved', 'AuctionController@approvedAuction')->name('auction.approved');
                Route::get('auction/unapproved', 'AuctionController@unapprovedAuction')->name('auction.unapproved');
                Route::get('auction/approve/{id}', 'AuctionController@approve')->name('auction.approve');
            });
           
            Route::namespace('Promotion')->group(function () {
                Route::get('editPromotion', 'PromotionController@editPromotion')->name('promotion.editPromotion');
                Route::put('updatePromotion', 'PromotionController@updatePromotion')->name('promotion.updatePromotion');
            });
            Route::namespace('Orders')->group(function () {
                Route::resource('orders', 'OrderController');
                Route::resource('order-statuses', 'OrderStatusController');
                Route::get('orders/{id}/invoice', 'OrderController@generateInvoice')->name('orders.invoice.generate');
            });
            Route::resource('addresses', 'Addresses\AddressController');
            Route::resource('countries', 'Countries\CountryController');
            Route::resource('countries.provinces', 'Provinces\ProvinceController');
            Route::resource('countries.provinces.cities', 'Cities\CityController');
            Route::resource('couriers', 'Couriers\CourierController');
            Route::resource('attributes', 'Attributes\AttributeController');
            Route::resource('attributes.values', 'Attributes\AttributeValueController');
            Route::resource('brands', 'Brands\BrandController');

        });
        Route::group(['middleware' => ['role:admin|superadmin, guard:employee']], function () {
            Route::resource('employees', 'EmployeeController');
            Route::get('employees/{id}/profile', 'EmployeeController@getProfile')->name('employee.profile');
            Route::put('employees/{id}/profile', 'EmployeeController@updateProfile')->name('employee.profile.update');
            Route::resource('roles', 'Roles\RoleController');
            Route::resource('permissions', 'Permissions\PermissionController');
        });
    });
});

/**
 * Frontend routes
 */
Auth::routes();
Route::namespace('Auth')->group(function () {
    Route::get('cart/login', 'CartLoginController@showLoginForm')->name('cart.login');
    Route::post('cart/login', 'CartLoginController@login')->name('cart.login');
    Route::get('logout', 'LoginController@logout');
});

Route::namespace('Front')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::group(['middleware' => ['auth', 'web']], function () {

        Route::namespace('Payments')->group(function () {
            Route::get('bank-transfer', 'BankTransferController@index')->name('bank-transfer.index');
            Route::post('bank-transfer', 'BankTransferController@store')->name('bank-transfer.store');
        });

        Route::namespace('Addresses')->group(function () {
            Route::resource('country.state', 'CountryStateController');
            Route::resource('state.city', 'StateCityController');
        });

        Route::get('accounts', 'AccountsController@index')->name('accounts');
        Route::get('checkout', 'CheckoutController@index')->name('checkout.index');
        Route::post('checkout', 'CheckoutController@store')->name('checkout.store');
        Route::get('checkout/execute', 'CheckoutController@executePayPalPayment')->name('checkout.execute');
        Route::post('checkout/execute', 'CheckoutController@charge')->name('checkout.execute');
        Route::get('checkout/cancel', 'CheckoutController@cancel')->name('checkout.cancel');
        Route::get('checkout/success', 'CheckoutController@success')->name('checkout.success');
        Route::resource('customer.address', 'CustomerAddressController');
    });
    Route::resource('cart', 'CartController');
    Route::get("category/{slug}", 'CategoryController@getCategory')->name('front.category.slug');
    Route::get("search", 'ProductController@search')->name('search.product');
    Route::get("{product}", 'ProductController@show')->name('front.get.product');

});

app/Http/Controllers/Admin/Categories/CategoryController.php
<?php

namespace App\Http\Controllers\Admin\Categories;

use App\Shop\Attributes\Attribute;
use App\Shop\Categories\Category;
use App\Shop\Categories\Repositories\CategoryRepository;
use App\Shop\Categories\Repositories\Interfaces\CategoryRepositoryInterface;
use App\Shop\Categories\Requests\CreateCategoryRequest;
use App\Shop\Categories\Requests\UpdateCategoryRequest;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * @var CategoryRepositoryInterface
     */
    private $categoryRepo;

    /**
     * CategoryController constructor.
     *
     * @param CategoryRepositoryInterface $categoryRepository
     */
    public function __construct(CategoryRepositoryInterface $categoryRepository)
    {
        $this->categoryRepo = $categoryRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = $this->categoryRepo->rootCategories('created_at', 'desc');
        $categories->map(function ($item)
        {
            $catRepo = new CategoryRepository($item);
            $attributes = $catRepo->listAttributes()->implode('name',' - ');
            $item->attributes = $attributes;
            return $item;
        });
        return view('admin.categories.list', [
            'categories' => $categories,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create', [
            'categories' => $this->categoryRepo->rootCategories('name','asc'),
            'attributes' => Attribute::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  CreateCategoryRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCategoryRequest $request)
    {
        $this->categoryRepo->createCategory($request->except('_token', '_method'));

        return redirect()->route('admin.categories.index')->with('message', 'Category created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = $this->categoryRepo->findCategoryById($id);
        $list = $category->children;

        $list->map(function($item)
        {
            $cat = Category::find($item->id);
            $catRepo = new CategoryRepository($cat);
            $item->attributes = $catRepo->listAttributes()->map(function ($item)
            {
                return $item->name;
            });
            $item->attributes = implode(" - ",$item->attributes->toArray());
            return $item;
        });

        $cat = new CategoryRepository($category);

        return view('admin.categories.show', [
            'category' => $category,
            'categories' => $category->children,
            'products' => $cat->findProducts()
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = $this->categoryRepo->findCategoryById($id);
        $categoryRepo = new CategoryRepository($category);
        $selectedAttributes = $categoryRepo->listAttributes()->pluck('id');
        return view('admin.categories.edit', [
            'categories' => $this->categoryRepo->rootCategories('name', 'asc', $id),
            'category' => $this->categoryRepo->findCategoryById($id),
            'attributes' => Attribute::all(),
            'categoryAttributes' => $selectedAttributes->toArray()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  UpdateCategoryRequest $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCategoryRequest $request, $id)
    {
        $category = $this->categoryRepo->findCategoryById($id);
        $update = new CategoryRepository($category);
        $update->updateCategory($request->except('_token', '_method'));

        if ($request->has('Attr')) {
            $update->syncAttributes($request->input('Attr'));
        } else {
            $update->detachAttributes();
        }

        $request->session()->flash('message', 'Update successful');
        return redirect()->route('admin.categories.edit', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(int $id)
    {
        $category = $this->categoryRepo->findCategoryById($id);
        $catRepo = new CategoryRepository($category);
        $catRepo->detachAttributes();
        $category->delete();

        request()->session()->flash('message', 'Delete successful');
        return redirect()->route('admin.categories.index');
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function removeImage(Request $request)
    {
        $categoryRepo = new CategoryRepository(Category::find($request->get('category')));
        $categoryRepo->deleteFile($request->only('category'));
        request()->session()->flash('message', 'Image delete successful');
        return redirect()->route('admin.categories.edit', $request->input('category'));
    }
}

app/Http/Controllers/Admin/Categories/Requests/CreateCategoryRequest.php
<?php

namespace App\Shop\Categories\Requests;

use App\Shop\Base\BaseFormRequest;

class CreateCategoryRequest extends BaseFormRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name' => ['required', 'unique:categories']
        ];
    }
}

app/Http/Controllers/Admin/Categories/Requests/UpdateCategoryRequest.php
<?php

namespace App\Shop\Categories\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class UpdateCategoryRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name' => ['required', Rule::unique('categories')->ignore(request()->segment(3))]
        ];
    }
}

app/Http/Controllers/Front/CategoryController.php
<?php

namespace App\Http\Controllers\Front;

use App\Shop\Categories\Repositories\CategoryRepository;
use App\Shop\Categories\Repositories\Interfaces\CategoryRepositoryInterface;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * @var CategoryRepositoryInterface
     */
    private $categoryRepo;

    /**
     * CategoryController constructor.
     *
     * @param CategoryRepositoryInterface $categoryRepository
     */
    public function __construct(CategoryRepositoryInterface $categoryRepository)
    {
        $this->categoryRepo = $categoryRepository;
    }

    

    /**
     * Find the category via the slug
     *
     * @param string $slug
     * @return \App\Shop\Categories\Category
     */
    public function getCategory(string $slug)
    {
        $category = $this->categoryRepo->findCategoryBySlug(['slug' => $slug]);

        $repo = new CategoryRepository($category);

        $products = $repo->findProducts()->where('status', 1)->all();

        return view('front.categories.category', [
            'category' => $category,
            'products' => $repo->paginateArrayResults($products, 20)
        ]);
    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.admin.app')

@section('content')
<!-- Main content -->
<section class="content" style="margin-top: 25px;" >
    @include('layouts.errors-and-messages')
    <div style="margin:0 auto; width:50%; border:none; text-align:center;">
        <h2>Add Category</h2>
    </div>
    <div class="box customBox">
        <form action="{{ route('admin.categories.store') }}" method="post" class="form" enctype="multipart/form-data">
            <div class="box-body">
                {{ csrf_field() }}
               <div class="form-group group mt-3">
                        <label for="parent">Parent Category</label>
                        <select name="parent" id="parent" class="form-control select2">
                            <option value="0">No Parent</option>
                            @foreach($categories as $category)
                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group group">
                    <label for="name">Category / Sub Category Name <span class="text-danger">*</span></label>
                    <input type="text" name="name" id="name" placeholder="Name" class="form-control"
                        value="{{ old('name') }}">
                    </div>
               

                <div class="form-group group">
                    <label for="iconCode">Category Icon Code <span class="text-danger">*</span></label>
                    <input type="text" name="icon_code" id="icon_code" placeholder="Icon Code" class="form-control">
                </div>

                <div class="form-group group">
                    <label for="icon_font">Category Icon Font <span class="text-danger">*</span></label>
                    <input type="text" name="icon_font" id="icon_font" placeholder="Icon Font" class="form-control">
                </div>

                <div class="hint">
                    <p style="padding: 5px;">
                        You can get Icon Code & Icon Font Family From <a class="flutterIcon" href="http://fluttericon.com/">Here</a>
                    </p>
                </div>

                <div class="form-group group">
                    <label for="f_color">Category First Color <span class="text-danger">*</span></label>
                    <input class="form-control" name="f_color" id="f_color" placeholder="First Color" type="text" />
                </div>

                <div class="form-group group">
                    <label for="l_color">Category Second Color <span class="text-danger">*</span></label>

                    <input class="form-control" name="l_color" id="l_color" placeholder="Second Color" type="text" />
                </div>

                <div class="group">
                    <label for="Attr">Category Attribues <span class="text-danger form-group">*</span></label>
                    <div id="Attr">
                        @foreach($attributes as $attr)
                        <input type="checkbox" name="Attr[]" value="{{ $attr->id }}"> &nbsp;{{ $attr->name }} <br />
                        @endforeach
                    </div>
                </div>
                <div class="form-group mt-3 group">
                    <label for="cover">Sub Category Cover </label>
                    <input type="file" name="cover" id="cover" class="form-control">
                </div>
                 <div class="form-group group">
                        <label for="status">Status </label>
                        <select name="status" id="status" class="form-control">
                            <option value="0">Disable</option>
                            <option value="1">Enable</option>
                        </select>
                    </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer" style="text-align:center;">
                <div class="btn-group" style="margin:0 auto;">
                    <a href="{{ route('admin.categories.index') }}" class="btn btn-default">Back</a>
                    <button type="submit" class="btn btn-primary">Create</button>
                </div>
            </div>
        </form>
    </div>
    <!-- /.box -->

</section>
<!-- /.content -->
@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin.app')

@section('content')
<!-- Main content -->
<section class="content" style="margin-top: 25px;" >
    @include('layouts.errors-and-messages')
    <div style="margin:0 auto; width:50%; border:none; text-align:center;">
        <h2>Edit Category</h2>
    </div>
    <div class="box customBox">
        <form action="{{ route('admin.categories.update', $category->id) }}" method="post" class="form"
            enctype="multipart/form-data">
            <div class="box-body">
                <input type="hidden" name="_method" value="put">
                {{ csrf_field() }}
                <div class="form-group group mt-3">
                        <label for="parent">Parent Category</label>
                        <select name="parent" id="parent" class="form-control select2">
                            <option value="0">No Parent</option>
                            @foreach($categories as $cat)
                                <option @if($cat->id == $category->parent_id) selected="selected" @endif value="{{$cat->id}}">{{$cat->name}}</option>
                            @endforeach
                        </select>
                    </div>
                <div class="form-group group">
                    <label for="name">Category Name <span class="text-danger">*</span></label>
                    <input type="text" name="name" id="name" placeholder="Name" class="form-control"
                        value="{!! $category->name ?: old('name')  !!}">
                </div>
                <div class="form-group group">
                    <label for="name">Category Slug <span class="text-danger">*</span></label>
                    <input type="text" name="slug" id="slug" placeholder="slug" class="form-control"
                        value="{!! $category->slug ?: old('slug')  !!}">
                </div>
                <div class="form-group group">
                    <label for="icon_code">Category Icon Code <span class="text-danger">*</span></label>
                    <input type="text" name="icon_code" id="icon_code" placeholder="Icon Code" class="form-control"
                        value="{!! $category->icon_code ?: old('icon_code')  !!}">
                </div>
                <div class="form-group group">
                    <label for="icon_font">Category Icon Font Family <span class="text-danger">*</span></label>
                    <input type="text" name="icon_font" id="icon_font" placeholder="Icon Font Family"
                        class="form-control" value="{!! $category->icon_font ?: old('icon_font')  !!}">
                </div>
                <div style="background-color:gold; text-align:center; margin:0 auto; width:50%;">
                    <p>
                        You can get Icon Code & Icon Font Family From <a href="http://fluttericon.com/">Here</a>
                    </p>
                </div>
                <div class="form-group group">
                    <label for="f_color">Category First Color <span class="text-danger">*</span></label>
                    <input type="text" name="f_color" id="f_color" placeholder="First Color" class="form-control"
                        value="{!! $category->f_color ?: old('f_color')  !!}">
                </div>
                <div class="form-group group">
                    <label for="l_color">Category Second Color <span class="text-danger">*</span></label>
                    <input type="text" name="l_color" id="l_color" placeholder="Second Color" class="form-control"
                        value="{!! $category->l_color ?: old('l_color')  !!}">
                </div>
                <div class="group">
                        <label for="Attr">Category Attributes <span class="text-danger form-group">*</span></label>
                    <div>
                        @foreach($attributes as $attr)
                            <input type="checkbox" name="Attr[]" value="{{ $attr->id }}" @if( in_array($attr->id, $categoryAttributes)) checked="checked" @endif > &nbsp;{{ $attr->name }}<br />
                        @endforeach
                    </div>
                </div>
            </div>

            <div class="group">
             @if(isset($category->cover))
                <div class="form-group mt-3">
                    <img class="mt-3" src="{{ asset("storage/$category->cover") }}" alt="" class="img-responsive">
                    <br />
                    <a onclick="return confirm('Are you sure?')"
                    href="{{ route('admin.category.remove.image', ['category' => $category->id]) }}"
                    class="btn btn-danger">Remove image?</a>
                </div>
                @endif
            </div>
                <div class="form-group mt-3 group"><div class=""><div class=""><div class="">

                </div></div></div>
                    <label for="cover">Cover </label>
                    <input type="file" name="cover" id="cover" class="form-control">
                </div>
                <div class="group">
                    <label for="status">Status </label>
                    <select name="status" id="status" class="form-control">
                        <option value="0" @if($category->status == 0) selected="selected" @endif>Disable</option>
                        <option value="1" @if($category->status == 1) selected="selected" @endif>Enable</option>
                    </select>
                </div>
</div>
    </div>
    <!-- /.box-body -->
    <div class="box-footer" style="text-align:center;">
        <div class="btn-group" style="margin:0 auto;">
            <a href="{{ route('admin.categories.index') }}" class="btn btn-default">Back</a>
            <button type="submit" class="btn btn-primary">Update</button>
        </div>
    </div>
    </form>
    </div>
    <!-- /.box -->

</section>
<!-- /.content -->
@endsection

resources/views/admin/categories/list.blade.php
@extends('layouts.admin.app')

@section('content')
    <!-- Main content -->
    <section class="content" style="margin-top: 25px;" >
    <div style="margin:0 auto; width:50%; border:none; text-align:center;">
<h2>Show Categories</h2>
</div>
    @include('layouts.errors-and-messages')
    <!-- Default box -->
        @if($categories)
            <div class="box">
                <div class="box-body">
                    <h2>Categories</h2>
                    <table class="table">
                       
                        
                        <thead>
                            <tr>
                                <td class="col-md-1">Name</td>
                                <td class="col-md-1">Slug</td>
                                <td class="col-md-1">Icon Code</td>
                                <td class="col-md-1">Icon Font Family</td>
                                <td class="col-md-1">First Color</td>
                                <td class="col-md-1">Second Color</td>
                                <td class="col-md-1">Attributes</td>
                                <td class="col-md-1">Status</td>
                                <td class="col-md-1">Actions</td>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach ($categories as $category)
                            <tr>
                                <td>
                                    <a href="{{ route('admin.categories.show', $category->id) }}">{{ $category->name }}</a>
                                </td>
                                <td>{{ $category->slug }}</td>
                                <td>{{ $category->icon_code }}</td>
                                <td>{{ $category->icon_font }}</td>
                                <td>{{ $category->f_color }}</td>
                                <td>{{ $category->l_color }}</td>
                                <td> {{ $category->attributes }}
                                </td>
                                <td>@include('layouts.status', ['status' => $category->status])</td>
                                <td>
                                    <form action="{{ route('admin.categories.destroy', $category->id) }}" method="post" class="form-horizontal">
                                        {{ csrf_field() }}
                                        <input type="hidden" name="_method" value="delete">
                                        <div class="btn-group">
                                            @if($category->name != "UnCategorized")
                                            <a href="{{ route('admin.categories.edit', $category->id) }}" class="btn btn-primary btn-sm"><i class="fa fa-edit"></i> Edit</a>
                                            <button onclick="return confirm('Are you sure?')" type="submit" class="btn btn-danger btn-sm"><i class="fa fa-times"></i> Delete</button>
                                            @endif
                                        </div>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
{{--                    {{ $categories->links() }}--}}
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        @endif

    </section>
    <!-- /.content -->
@endsection